module.exports = {
  apps: [
    {
      name: 'office-api-a',
      script: 'server/index.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '400M',
      min_uptime: '30s',
      max_restarts: 20,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      time: true,
      env: {
        NODE_ENV: 'production',
        PORT: '5000',
        STRICT_DB_TARGET: 'true',
        STRICT_DB_CONNECTIVITY_EXIT: 'false',
        FATAL_ON_UNHANDLED: 'false',
        DB_VERIFY_RETRIES: '5',
        READY_GRACE_PERIOD_MS: '45000',
        READY_PROBE_RETRIES: '2',
        DB_KEEPALIVE_PING_INTERVAL_MS: '30000',
        DB_POOL_MAX: '25',
        DB_POOL_MAX_USES: '7500',
        SERVER_KEEPALIVE_TIMEOUT_MS: '65000',
        SERVER_HEADERS_TIMEOUT_MS: '70000',
        SERVER_REQUEST_TIMEOUT_MS: '120000',
      },
    },
    {
      name: 'office-api-b',
      script: 'server/index.js',
      cwd: __dirname,
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '400M',
      min_uptime: '30s',
      max_restarts: 20,
      restart_delay: 5000,
      exp_backoff_restart_delay: 200,
      time: true,
      env: {
        NODE_ENV: 'production',
        PORT: '5001',
        STRICT_DB_TARGET: 'true',
        STRICT_DB_CONNECTIVITY_EXIT: 'false',
        FATAL_ON_UNHANDLED: 'false',
        DB_VERIFY_RETRIES: '5',
        READY_GRACE_PERIOD_MS: '45000',
        READY_PROBE_RETRIES: '2',
        DB_KEEPALIVE_PING_INTERVAL_MS: '30000',
        DB_POOL_MAX: '25',
        DB_POOL_MAX_USES: '7500',
        SERVER_KEEPALIVE_TIMEOUT_MS: '65000',
        SERVER_HEADERS_TIMEOUT_MS: '70000',
        SERVER_REQUEST_TIMEOUT_MS: '120000',
      },
    },
  ],
};
