import apiClient from '../config/axiosConfig';

export const getAssetSummary = async () => (await apiClient.get('/api/assets/summary')).data;
export const getAssetReports = async () => (await apiClient.get('/api/assets/reports')).data;
export const getAssetMasters = async () => (await apiClient.get('/api/assets/masters')).data;
export const getAssets = async (params = {}) => (await apiClient.get('/api/assets', { params })).data;
export const saveAsset = async (payload) => (await apiClient.post('/api/assets', payload)).data;
export const updateAsset = async (id, payload) => (await apiClient.put(`/api/assets/${id}`, payload)).data;
export const getAssetComponents = async (assetId) => (await apiClient.get(`/api/assets/${assetId}/components`)).data;
export const addAssetComponent = async (assetId, payload) => (await apiClient.post(`/api/assets/${assetId}/components`, payload)).data;
export const updateAssetComponent = async (componentId, payload) => (await apiClient.put(`/api/assets/components/${componentId}`, payload)).data;
export const replaceAssetComponent = async (componentId, payload) => (await apiClient.post(`/api/assets/components/${componentId}/replace`, payload)).data;
export const getAssetComponentMovements = async (assetId) => (await apiClient.get(`/api/assets/${assetId}/component-movements`)).data;
export const updateAssetDesk = async (id, payload) => (await apiClient.put(`/api/assets/desks/${id}`, payload)).data;
export const getAssetDeskHistory = async (id) => (await apiClient.get(`/api/assets/desks/${id}/history`)).data;
export const moveAsset = async (id, payload) => (await apiClient.post(`/api/assets/${id}/move`, payload)).data;
export const getAssetMovements = async (params = {}) => (await apiClient.get('/api/assets/movements', { params })).data;
export const getAssetWarranties = async () => (await apiClient.get('/api/assets/warranties')).data;
export const saveAssetWarranty = async (payload) => (await apiClient.post('/api/assets/warranties', payload)).data;
export const getAssetIssues = async () => (await apiClient.get('/api/assets/issues')).data;
export const saveAssetIssue = async (payload) => (await apiClient.post('/api/assets/issues', payload)).data;
export const updateAssetIssueStatus = async (id, payload) => (await apiClient.patch(`/api/assets/issues/${id}`, payload)).data;
export const getAssetRepairs = async () => (await apiClient.get('/api/assets/repairs')).data;
export const saveAssetRepair = async (payload) => (await apiClient.post('/api/assets/repairs', payload)).data;
export const getAssetReplacements = async () => (await apiClient.get('/api/assets/replacements')).data;
export const saveAssetReplacement = async (payload) => (await apiClient.post('/api/assets/replacements', payload)).data;
export const getAssetStockItems = async () => (await apiClient.get('/api/assets/stock-items')).data;
export const saveAssetStockItem = async (payload) => (await apiClient.post('/api/assets/stock-items', payload)).data;
export const updateAssetStockItem = async (id, payload) => (await apiClient.put(`/api/assets/stock-items/${id}`, payload)).data;
export const getAssetStockMovements = async (params = {}) => (await apiClient.get('/api/assets/stock-movements', { params })).data;
export const saveAssetStockMovement = async (payload) => (await apiClient.post('/api/assets/stock-movements', payload)).data;
